<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodGlycemicSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $foods = [
            // ── Grains & Rice ─────────────────────────────
            ['food_item' => 'White Rice',          'category' => 'grain',     'glycemic_index' => 73, 'glycemic_load' => 30, 'typical_spike_mg_dl' => 55, 'peak_time_minutes' => 45, 'recovery_time_minutes' => 120, 'serving_size' => '1 cup cooked',   'alternatives' => '["Brown Rice","Quinoa","Cauliflower Rice"]'],
            ['food_item' => 'Brown Rice',          'category' => 'grain',     'glycemic_index' => 50, 'glycemic_load' => 16, 'typical_spike_mg_dl' => 25, 'peak_time_minutes' => 60, 'recovery_time_minutes' => 90,  'serving_size' => '1 cup cooked',   'alternatives' => '["Quinoa","Millets","Barley"]'],
            ['food_item' => 'Basmati Rice',        'category' => 'grain',     'glycemic_index' => 58, 'glycemic_load' => 22, 'typical_spike_mg_dl' => 35, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 100, 'serving_size' => '1 cup cooked',   'alternatives' => '["Brown Basmati","Quinoa","Foxtail Millet"]'],
            ['food_item' => 'Biryani',             'category' => 'grain',     'glycemic_index' => 65, 'glycemic_load' => 28, 'typical_spike_mg_dl' => 45, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 110, 'serving_size' => '1 plate',        'alternatives' => '["Brown Rice Pulao","Quinoa Biryani","Millets Khichdi"]'],
            ['food_item' => 'Oats',                'category' => 'grain',     'glycemic_index' => 55, 'glycemic_load' => 13, 'typical_spike_mg_dl' => 20, 'peak_time_minutes' => 45, 'recovery_time_minutes' => 80,  'serving_size' => '1 cup cooked',   'alternatives' => '["Steel-cut Oats","Daliya","Ragi Porridge"]'],
            ['food_item' => 'Quinoa',              'category' => 'grain',     'glycemic_index' => 53, 'glycemic_load' => 13, 'typical_spike_mg_dl' => 18, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 75,  'serving_size' => '1 cup cooked',   'alternatives' => '["Foxtail Millet","Amaranth","Buckwheat"]'],
            ['food_item' => 'Poha',                'category' => 'grain',     'glycemic_index' => 64, 'glycemic_load' => 22, 'typical_spike_mg_dl' => 35, 'peak_time_minutes' => 40, 'recovery_time_minutes' => 90,  'serving_size' => '1 bowl',         'alternatives' => '["Oats Poha","Vegetable Upma","Sprouts Chaat"]'],
            ['food_item' => 'Upma',                'category' => 'grain',     'glycemic_index' => 60, 'glycemic_load' => 18, 'typical_spike_mg_dl' => 30, 'peak_time_minutes' => 40, 'recovery_time_minutes' => 85,  'serving_size' => '1 bowl',         'alternatives' => '["Oats Upma","Ragi Upma","Vegetable Daliya"]'],
            ['food_item' => 'Daliya',              'category' => 'grain',     'glycemic_index' => 48, 'glycemic_load' => 12, 'typical_spike_mg_dl' => 18, 'peak_time_minutes' => 55, 'recovery_time_minutes' => 75,  'serving_size' => '1 bowl',         'alternatives' => '["Oats","Ragi Porridge","Quinoa"]'],
            ['food_item' => 'Foxtail Millet',      'category' => 'grain',     'glycemic_index' => 50, 'glycemic_load' => 14, 'typical_spike_mg_dl' => 20, 'peak_time_minutes' => 55, 'recovery_time_minutes' => 80,  'serving_size' => '1 cup cooked',   'alternatives' => '["Quinoa","Barnyard Millet","Amaranth"]'],
            ['food_item' => 'Ragi',                'category' => 'grain',     'glycemic_index' => 54, 'glycemic_load' => 15, 'typical_spike_mg_dl' => 22, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 80,  'serving_size' => '1 cup cooked',   'alternatives' => '["Foxtail Millet","Quinoa","Oats"]'],

            // ── Breads ────────────────────────────────────
            ['food_item' => 'White Bread',         'category' => 'bread',     'glycemic_index' => 75, 'glycemic_load' => 11, 'typical_spike_mg_dl' => 45, 'peak_time_minutes' => 30, 'recovery_time_minutes' => 90,  'serving_size' => '2 slices',       'alternatives' => '["Whole Wheat Bread","Multigrain Bread","Ragi Bread"]'],
            ['food_item' => 'Whole Wheat Bread',   'category' => 'bread',     'glycemic_index' => 54, 'glycemic_load' => 7,  'typical_spike_mg_dl' => 22, 'peak_time_minutes' => 40, 'recovery_time_minutes' => 70,  'serving_size' => '2 slices',       'alternatives' => '["Multigrain Bread","Ragi Bread","Oat Bread"]'],
            ['food_item' => 'Roti',                'category' => 'bread',     'glycemic_index' => 62, 'glycemic_load' => 15, 'typical_spike_mg_dl' => 25, 'peak_time_minutes' => 40, 'recovery_time_minutes' => 80,  'serving_size' => '2 rotis',        'alternatives' => '["Bajra Roti","Jowar Roti","Ragi Roti"]'],
            ['food_item' => 'Naan',                'category' => 'bread',     'glycemic_index' => 71, 'glycemic_load' => 20, 'typical_spike_mg_dl' => 40, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 95,  'serving_size' => '1 naan',         'alternatives' => '["Whole Wheat Roti","Bajra Roti","Jowar Roti"]'],
            ['food_item' => 'Paratha',             'category' => 'bread',     'glycemic_index' => 67, 'glycemic_load' => 18, 'typical_spike_mg_dl' => 35, 'peak_time_minutes' => 40, 'recovery_time_minutes' => 90,  'serving_size' => '1 paratha',      'alternatives' => '["Roti","Bajra Roti","Multigrain Paratha"]'],
            ['food_item' => 'Dosa',                'category' => 'bread',     'glycemic_index' => 66, 'glycemic_load' => 17, 'typical_spike_mg_dl' => 32, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 85,  'serving_size' => '2 dosas',        'alternatives' => '["Ragi Dosa","Moong Dal Dosa","Oats Dosa"]'],
            ['food_item' => 'Idli',                'category' => 'bread',     'glycemic_index' => 60, 'glycemic_load' => 14, 'typical_spike_mg_dl' => 28, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 80,  'serving_size' => '3 idlis',        'alternatives' => '["Ragi Idli","Oats Idli","Moong Dal Idli"]'],
            ['food_item' => 'Puri',                'category' => 'bread',     'glycemic_index' => 72, 'glycemic_load' => 22, 'typical_spike_mg_dl' => 42, 'peak_time_minutes' => 30, 'recovery_time_minutes' => 95,  'serving_size' => '3 puris',        'alternatives' => '["Roti","Bajra Roti","Baked whole wheat puri"]'],
            ['food_item' => 'Bajra Roti',          'category' => 'bread',     'glycemic_index' => 52, 'glycemic_load' => 12, 'typical_spike_mg_dl' => 20, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 75,  'serving_size' => '2 rotis',        'alternatives' => '["Jowar Roti","Ragi Roti","Multigrain Roti"]'],
            ['food_item' => 'Jowar Roti',          'category' => 'bread',     'glycemic_index' => 50, 'glycemic_load' => 11, 'typical_spike_mg_dl' => 18, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 70,  'serving_size' => '2 rotis',        'alternatives' => '["Bajra Roti","Ragi Roti","Multigrain Roti"]'],

            // ── Sweets & Desserts ─────────────────────────
            ['food_item' => 'Jalebi',              'category' => 'sweet',     'glycemic_index' => 85, 'glycemic_load' => 38, 'typical_spike_mg_dl' => 70, 'peak_time_minutes' => 25, 'recovery_time_minutes' => 130, 'serving_size' => '2 pieces',       'alternatives' => '["Dates","Dark Chocolate (85%+)","Sugar-free Laddu"]'],
            ['food_item' => 'Gulab Jamun',         'category' => 'sweet',     'glycemic_index' => 80, 'glycemic_load' => 35, 'typical_spike_mg_dl' => 65, 'peak_time_minutes' => 25, 'recovery_time_minutes' => 125, 'serving_size' => '2 pieces',       'alternatives' => '["Dates","Anjeer Barfi","Sugar-free Rasgulla"]'],
            ['food_item' => 'Rasgulla',            'category' => 'sweet',     'glycemic_index' => 78, 'glycemic_load' => 32, 'typical_spike_mg_dl' => 60, 'peak_time_minutes' => 25, 'recovery_time_minutes' => 120, 'serving_size' => '2 pieces',       'alternatives' => '["Paneer in milk","Makhana Kheer","Sugar-free Rasgulla"]'],
            ['food_item' => 'Halwa',               'category' => 'sweet',     'glycemic_index' => 76, 'glycemic_load' => 30, 'typical_spike_mg_dl' => 55, 'peak_time_minutes' => 30, 'recovery_time_minutes' => 115, 'serving_size' => '1 bowl',         'alternatives' => '["Oats Halwa","Ragi Halwa","Lauki Halwa"]'],
            ['food_item' => 'Laddu',               'category' => 'sweet',     'glycemic_index' => 74, 'glycemic_load' => 28, 'typical_spike_mg_dl' => 50, 'peak_time_minutes' => 30, 'recovery_time_minutes' => 110, 'serving_size' => '2 pieces',       'alternatives' => '["Dry Fruit Laddu","Ragi Laddu","Dates Laddu"]'],
            ['food_item' => 'Kheer',               'category' => 'sweet',     'glycemic_index' => 72, 'glycemic_load' => 26, 'typical_spike_mg_dl' => 45, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 105, 'serving_size' => '1 bowl',         'alternatives' => '["Oats Kheer","Makhana Kheer","Sugar-free Phirni"]'],
            ['food_item' => 'Cake',                'category' => 'sweet',     'glycemic_index' => 82, 'glycemic_load' => 36, 'typical_spike_mg_dl' => 60, 'peak_time_minutes' => 25, 'recovery_time_minutes' => 120, 'serving_size' => '1 slice',        'alternatives' => '["Ragi Cake","Oats Cookies","Dark Chocolate"]'],
            ['food_item' => 'Ice Cream',           'category' => 'sweet',     'glycemic_index' => 62, 'glycemic_load' => 18, 'typical_spike_mg_dl' => 35, 'peak_time_minutes' => 40, 'recovery_time_minutes' => 90,  'serving_size' => '1 scoop',        'alternatives' => '["Frozen Yogurt","Fruit Sorbet","Banana Ice Cream"]'],

            // ── Snacks ────────────────────────────────────
            ['food_item' => 'Samosa',              'category' => 'snack',     'glycemic_index' => 68, 'glycemic_load' => 24, 'typical_spike_mg_dl' => 40, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 95,  'serving_size' => '2 pieces',       'alternatives' => '["Baked Samosa","Sprouts Chaat","Dhokla"]'],
            ['food_item' => 'Pizza',               'category' => 'snack',     'glycemic_index' => 60, 'glycemic_load' => 22, 'typical_spike_mg_dl' => 35, 'peak_time_minutes' => 45, 'recovery_time_minutes' => 100, 'serving_size' => '2 slices',       'alternatives' => '["Whole Wheat Base Pizza","Vegetable Wrap","Stuffed Roti"]'],
            ['food_item' => 'French Fries',        'category' => 'snack',     'glycemic_index' => 75, 'glycemic_load' => 25, 'typical_spike_mg_dl' => 50, 'peak_time_minutes' => 30, 'recovery_time_minutes' => 100, 'serving_size' => '1 medium',       'alternatives' => '["Baked Sweet Potato Wedges","Air-fried Vegetables","Roasted Chickpeas"]'],
            ['food_item' => 'Pakora',              'category' => 'snack',     'glycemic_index' => 65, 'glycemic_load' => 18, 'typical_spike_mg_dl' => 35, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 85,  'serving_size' => '5 pieces',       'alternatives' => '["Baked Pakora","Steamed Momos","Grilled Paneer"]'],
            ['food_item' => 'Bhel Puri',           'category' => 'snack',     'glycemic_index' => 62, 'glycemic_load' => 16, 'typical_spike_mg_dl' => 30, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 80,  'serving_size' => '1 bowl',         'alternatives' => '["Sprouts Chaat","Fruit Chaat","Roasted Makhana"]'],
            ['food_item' => 'Vada Pav',            'category' => 'snack',     'glycemic_index' => 70, 'glycemic_load' => 22, 'typical_spike_mg_dl' => 42, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 95,  'serving_size' => '1 piece',        'alternatives' => '["Dhokla","Sprouts Sandwich","Grilled Paneer Wrap"]'],
            ['food_item' => 'Dhokla',              'category' => 'snack',     'glycemic_index' => 45, 'glycemic_load' => 10, 'typical_spike_mg_dl' => 15, 'peak_time_minutes' => 40, 'recovery_time_minutes' => 65,  'serving_size' => '3 pieces',       'alternatives' => '["Steamed Idli","Sprouts Chaat","Moong Dal Cheela"]'],
            ['food_item' => 'Chips',               'category' => 'snack',     'glycemic_index' => 56, 'glycemic_load' => 15, 'typical_spike_mg_dl' => 28, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 80,  'serving_size' => '1 small packet', 'alternatives' => '["Roasted Makhana","Mixed Nuts","Baked Chips"]'],
            ['food_item' => 'Roasted Makhana',     'category' => 'snack',     'glycemic_index' => 38, 'glycemic_load' => 8,  'typical_spike_mg_dl' => 10, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 55,  'serving_size' => '1 bowl',         'alternatives' => '["Mixed Nuts","Roasted Chickpeas","Seeds Mix"]'],

            // ── Legumes & Lentils ─────────────────────────
            ['food_item' => 'Dal',                 'category' => 'legume',    'glycemic_index' => 42, 'glycemic_load' => 10, 'typical_spike_mg_dl' => 15, 'peak_time_minutes' => 55, 'recovery_time_minutes' => 70,  'serving_size' => '1 bowl',         'alternatives' => '["Moong Dal","Masoor Dal","Chana Dal"]'],
            ['food_item' => 'Rajma',               'category' => 'legume',    'glycemic_index' => 29, 'glycemic_load' => 7,  'typical_spike_mg_dl' => 10, 'peak_time_minutes' => 60, 'recovery_time_minutes' => 65,  'serving_size' => '1 bowl',         'alternatives' => '["Chana","Lobia","Moong Sprouts"]'],
            ['food_item' => 'Chole',               'category' => 'legume',    'glycemic_index' => 33, 'glycemic_load' => 8,  'typical_spike_mg_dl' => 12, 'peak_time_minutes' => 60, 'recovery_time_minutes' => 65,  'serving_size' => '1 bowl',         'alternatives' => '["Rajma","Moong Dal","Sprouts Salad"]'],
            ['food_item' => 'Sprouts',             'category' => 'legume',    'glycemic_index' => 25, 'glycemic_load' => 5,  'typical_spike_mg_dl' => 8,  'peak_time_minutes' => 60, 'recovery_time_minutes' => 55,  'serving_size' => '1 bowl',         'alternatives' => '["Mixed Sprouts Chaat","Moong Salad","Chana Chaat"]'],
            ['food_item' => 'Dal Khichdi',         'category' => 'legume',    'glycemic_index' => 55, 'glycemic_load' => 16, 'typical_spike_mg_dl' => 25, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 85,  'serving_size' => '1 bowl',         'alternatives' => '["Moong Dal Khichdi","Daliya Khichdi","Quinoa Khichdi"]'],

            // ── Dairy ─────────────────────────────────────
            ['food_item' => 'Paneer Tikka',        'category' => 'dairy',     'glycemic_index' => 20, 'glycemic_load' => 2,  'typical_spike_mg_dl' => 5,  'peak_time_minutes' => 60, 'recovery_time_minutes' => 50,  'serving_size' => '6 pieces',       'alternatives' => '["Grilled Tofu","Soy Chunks","Mushroom Tikka"]'],
            ['food_item' => 'Yogurt',              'category' => 'dairy',     'glycemic_index' => 36, 'glycemic_load' => 6,  'typical_spike_mg_dl' => 10, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 55,  'serving_size' => '1 cup',          'alternatives' => '["Greek Yogurt","Buttermilk","Lassi (no sugar)"]'],
            ['food_item' => 'Curd',                'category' => 'dairy',     'glycemic_index' => 36, 'glycemic_load' => 6,  'typical_spike_mg_dl' => 10, 'peak_time_minutes' => 50, 'recovery_time_minutes' => 55,  'serving_size' => '1 cup',          'alternatives' => '["Greek Yogurt","Buttermilk","Raita"]'],
            ['food_item' => 'Lassi',               'category' => 'dairy',     'glycemic_index' => 55, 'glycemic_load' => 14, 'typical_spike_mg_dl' => 22, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 70,  'serving_size' => '1 glass',        'alternatives' => '["Buttermilk","Lassi (no sugar)","Coconut Water"]'],
            ['food_item' => 'Milk',                'category' => 'dairy',     'glycemic_index' => 31, 'glycemic_load' => 4,  'typical_spike_mg_dl' => 8,  'peak_time_minutes' => 45, 'recovery_time_minutes' => 50,  'serving_size' => '1 glass',        'alternatives' => '["Almond Milk","Soy Milk","Buttermilk"]'],

            // ── Vegetables ────────────────────────────────
            ['food_item' => 'Potato',              'category' => 'vegetable', 'glycemic_index' => 78, 'glycemic_load' => 21, 'typical_spike_mg_dl' => 45, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 100, 'serving_size' => '1 medium',       'alternatives' => '["Sweet Potato","Cauliflower","Turnip"]'],
            ['food_item' => 'Sweet Potato',        'category' => 'vegetable', 'glycemic_index' => 54, 'glycemic_load' => 12, 'typical_spike_mg_dl' => 22, 'peak_time_minutes' => 45, 'recovery_time_minutes' => 75,  'serving_size' => '1 medium',       'alternatives' => '["Cauliflower","Pumpkin","Beetroot"]'],
            ['food_item' => 'Green Salad',         'category' => 'vegetable', 'glycemic_index' => 15, 'glycemic_load' => 1,  'typical_spike_mg_dl' => 3,  'peak_time_minutes' => 60, 'recovery_time_minutes' => 40,  'serving_size' => '1 large bowl',   'alternatives' => '["Mixed Vegetable Soup","Steamed Vegetables","Grilled Vegetables"]'],
            ['food_item' => 'Aloo Gobi',           'category' => 'vegetable', 'glycemic_index' => 65, 'glycemic_load' => 16, 'typical_spike_mg_dl' => 30, 'peak_time_minutes' => 40, 'recovery_time_minutes' => 85,  'serving_size' => '1 bowl',         'alternatives' => '["Gobi Matar","Mixed Vegetable Sabzi","Palak Paneer"]'],
            ['food_item' => 'Palak Paneer',        'category' => 'vegetable', 'glycemic_index' => 25, 'glycemic_load' => 4,  'typical_spike_mg_dl' => 8,  'peak_time_minutes' => 55, 'recovery_time_minutes' => 50,  'serving_size' => '1 bowl',         'alternatives' => '["Palak Tofu","Methi Paneer","Saag"]'],
            ['food_item' => 'Mixed Vegetables',    'category' => 'vegetable', 'glycemic_index' => 35, 'glycemic_load' => 5,  'typical_spike_mg_dl' => 8,  'peak_time_minutes' => 55, 'recovery_time_minutes' => 55,  'serving_size' => '1 bowl',         'alternatives' => '["Steamed Vegetables","Grilled Vegetables","Vegetable Soup"]'],

            // ── Fruits ────────────────────────────────────
            ['food_item' => 'Banana',              'category' => 'fruit',     'glycemic_index' => 62, 'glycemic_load' => 16, 'typical_spike_mg_dl' => 28, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 75,  'serving_size' => '1 medium',       'alternatives' => '["Apple","Pear","Guava"]'],
            ['food_item' => 'Mango',               'category' => 'fruit',     'glycemic_index' => 56, 'glycemic_load' => 14, 'typical_spike_mg_dl' => 25, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 70,  'serving_size' => '1 cup sliced',   'alternatives' => '["Papaya","Berries","Guava"]'],
            ['food_item' => 'Apple',               'category' => 'fruit',     'glycemic_index' => 36, 'glycemic_load' => 6,  'typical_spike_mg_dl' => 10, 'peak_time_minutes' => 45, 'recovery_time_minutes' => 55,  'serving_size' => '1 medium',       'alternatives' => '["Pear","Guava","Berries"]'],
            ['food_item' => 'Watermelon',          'category' => 'fruit',     'glycemic_index' => 72, 'glycemic_load' => 5,  'typical_spike_mg_dl' => 15, 'peak_time_minutes' => 25, 'recovery_time_minutes' => 60,  'serving_size' => '1 cup diced',    'alternatives' => '["Cucumber","Muskmelon","Papaya"]'],
            ['food_item' => 'Grapes',              'category' => 'fruit',     'glycemic_index' => 59, 'glycemic_load' => 11, 'typical_spike_mg_dl' => 20, 'peak_time_minutes' => 30, 'recovery_time_minutes' => 65,  'serving_size' => '1 cup',          'alternatives' => '["Berries","Pomegranate","Guava"]'],
            ['food_item' => 'Dates',               'category' => 'fruit',     'glycemic_index' => 42, 'glycemic_load' => 18, 'typical_spike_mg_dl' => 22, 'peak_time_minutes' => 40, 'recovery_time_minutes' => 70,  'serving_size' => '3 pieces',       'alternatives' => '["Figs","Anjeer","Prunes"]'],
            ['food_item' => 'Guava',               'category' => 'fruit',     'glycemic_index' => 12, 'glycemic_load' => 2,  'typical_spike_mg_dl' => 4,  'peak_time_minutes' => 55, 'recovery_time_minutes' => 40,  'serving_size' => '1 medium',       'alternatives' => '["Apple","Pear","Jamun"]'],

            // ── Beverages ─────────────────────────────────
            ['food_item' => 'Soda',                'category' => 'beverage',  'glycemic_index' => 87, 'glycemic_load' => 35, 'typical_spike_mg_dl' => 65, 'peak_time_minutes' => 20, 'recovery_time_minutes' => 110, 'serving_size' => '1 can (330ml)',  'alternatives' => '["Lemon Water","Buttermilk","Green Tea"]'],
            ['food_item' => 'Fruit Juice',         'category' => 'beverage',  'glycemic_index' => 70, 'glycemic_load' => 22, 'typical_spike_mg_dl' => 40, 'peak_time_minutes' => 20, 'recovery_time_minutes' => 85,  'serving_size' => '1 glass',        'alternatives' => '["Whole Fruit","Vegetable Juice","Coconut Water"]'],
            ['food_item' => 'Chai (with sugar)',    'category' => 'beverage',  'glycemic_index' => 58, 'glycemic_load' => 10, 'typical_spike_mg_dl' => 18, 'peak_time_minutes' => 25, 'recovery_time_minutes' => 60,  'serving_size' => '1 cup',          'alternatives' => '["Green Tea","Black Coffee","Chai (no sugar)"]'],
            ['food_item' => 'Green Tea',           'category' => 'beverage',  'glycemic_index' => 0,  'glycemic_load' => 0,  'typical_spike_mg_dl' => 0,  'peak_time_minutes' => 0,  'recovery_time_minutes' => 0,   'serving_size' => '1 cup',          'alternatives' => '["Black Coffee","Herbal Tea","Lemon Water"]'],
            ['food_item' => 'Coconut Water',       'category' => 'beverage',  'glycemic_index' => 54, 'glycemic_load' => 8,  'typical_spike_mg_dl' => 12, 'peak_time_minutes' => 25, 'recovery_time_minutes' => 50,  'serving_size' => '1 glass',        'alternatives' => '["Lemon Water","Buttermilk","Green Tea"]'],
            ['food_item' => 'Buttermilk',          'category' => 'beverage',  'glycemic_index' => 32, 'glycemic_load' => 4,  'typical_spike_mg_dl' => 6,  'peak_time_minutes' => 40, 'recovery_time_minutes' => 45,  'serving_size' => '1 glass',        'alternatives' => '["Coconut Water","Lemon Water","Raita"]'],
            ['food_item' => 'Sugar',               'category' => 'beverage',  'glycemic_index' => 92, 'glycemic_load' => 40, 'typical_spike_mg_dl' => 72, 'peak_time_minutes' => 15, 'recovery_time_minutes' => 120, 'serving_size' => '2 tsp',          'alternatives' => '["Stevia","Jaggery (moderation)","Honey (small amount)"]'],
            ['food_item' => 'Candy',               'category' => 'sweet',     'glycemic_index' => 88, 'glycemic_load' => 36, 'typical_spike_mg_dl' => 68, 'peak_time_minutes' => 15, 'recovery_time_minutes' => 115, 'serving_size' => '3 pieces',       'alternatives' => '["Dark Chocolate (85%+)","Dates","Mixed Nuts"]'],

            // ── Indian Curries & Dishes ───────────────────
            ['food_item' => 'Butter Chicken',      'category' => 'dish',      'glycemic_index' => 30, 'glycemic_load' => 5,  'typical_spike_mg_dl' => 10, 'peak_time_minutes' => 55, 'recovery_time_minutes' => 60,  'serving_size' => '1 bowl',         'alternatives' => '["Tandoori Chicken","Grilled Fish","Chicken Tikka"]'],
            ['food_item' => 'Chana Masala',        'category' => 'dish',      'glycemic_index' => 36, 'glycemic_load' => 9,  'typical_spike_mg_dl' => 14, 'peak_time_minutes' => 55, 'recovery_time_minutes' => 65,  'serving_size' => '1 bowl',         'alternatives' => '["Rajma","Sprouts Curry","Mixed Dal"]'],
            ['food_item' => 'Paneer Butter Masala', 'category' => 'dish',     'glycemic_index' => 28, 'glycemic_load' => 4,  'typical_spike_mg_dl' => 8,  'peak_time_minutes' => 55, 'recovery_time_minutes' => 55,  'serving_size' => '1 bowl',         'alternatives' => '["Palak Paneer","Paneer Tikka","Tofu Curry"]'],
            ['food_item' => 'Egg Curry',           'category' => 'dish',      'glycemic_index' => 22, 'glycemic_load' => 3,  'typical_spike_mg_dl' => 5,  'peak_time_minutes' => 55, 'recovery_time_minutes' => 50,  'serving_size' => '2 eggs + gravy', 'alternatives' => '["Boiled Eggs","Egg Bhurji","Tofu Bhurji"]'],

            // ── Other Common Foods ────────────────────────
            ['food_item' => 'Nuts',                'category' => 'snack',     'glycemic_index' => 15, 'glycemic_load' => 1,  'typical_spike_mg_dl' => 3,  'peak_time_minutes' => 60, 'recovery_time_minutes' => 40,  'serving_size' => '1 handful',      'alternatives' => '["Seeds Mix","Roasted Makhana","Trail Mix"]'],
            ['food_item' => 'Lentils',             'category' => 'legume',    'glycemic_index' => 30, 'glycemic_load' => 5,  'typical_spike_mg_dl' => 10, 'peak_time_minutes' => 60, 'recovery_time_minutes' => 60,  'serving_size' => '1 cup cooked',   'alternatives' => '["Moong Dal","Masoor Dal","Sprouts"]'],
            ['food_item' => 'Maida',               'category' => 'grain',     'glycemic_index' => 85, 'glycemic_load' => 35, 'typical_spike_mg_dl' => 60, 'peak_time_minutes' => 25, 'recovery_time_minutes' => 120, 'serving_size' => '1 cup',          'alternatives' => '["Whole Wheat Atta","Bajra Flour","Ragi Flour"]'],
            ['food_item' => 'Pasta',               'category' => 'grain',     'glycemic_index' => 55, 'glycemic_load' => 18, 'typical_spike_mg_dl' => 28, 'peak_time_minutes' => 45, 'recovery_time_minutes' => 85,  'serving_size' => '1 cup cooked',   'alternatives' => '["Whole Wheat Pasta","Zucchini Noodles","Quinoa Pasta"]'],
            ['food_item' => 'Maggi Noodles',       'category' => 'snack',     'glycemic_index' => 68, 'glycemic_load' => 24, 'typical_spike_mg_dl' => 38, 'peak_time_minutes' => 30, 'recovery_time_minutes' => 90,  'serving_size' => '1 packet',       'alternatives' => '["Vegetable Soup","Oats","Daliya"]'],
            ['food_item' => 'Pav Bhaji',           'category' => 'dish',      'glycemic_index' => 70, 'glycemic_load' => 25, 'typical_spike_mg_dl' => 42, 'peak_time_minutes' => 35, 'recovery_time_minutes' => 95,  'serving_size' => '1 plate',        'alternatives' => '["Mixed Vegetable Sabzi","Dhokla","Sprouts"]'],
        ];

        foreach ($foods as &$food) {
            $food['created_at'] = $now;
            $food['updated_at'] = $now;
        }
        unset($food);

        DB::table('food_glycemic_data')->insertOrIgnore($foods);
    }
}
